draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: true
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
    fa_solid: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/refs/heads/7.x/svgs/solid/{}.svg
    fa_regular: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/refs/heads/7.x/svgs/regular/{}.svg
    phosphor: https://unpkg.com/@phosphor-icons/core/assets/{}.svg
    simple_icons: https://raw.githubusercontent.com/simple-icons/simple-icons/refs/heads/develop/icons/{}.svg
    lucide: https://raw.githubusercontent.com/lucide-icons/lucide/refs/heads/main/icons/{}.svg
    feather: https://raw.githubusercontent.com/feathericons/feather/refs/heads/main/icons/{}.svg
  svg_extra_style: |
    .glyph:not(.simple_icons\:tmux),
    .glyph:not(.simple_icons\:tmux) * {
      color: white !important;
      fill: white !important;
      stroke: white !important;
    }
  use_local_cache: true

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$

  raw_binding_map:
    "&equals_arrow":
      tap: "=>"
    "&minus_arrow":
      tap: "->"
    "&colon_equals":
      tap: ":="

    # Mouse Scroll
    "&msc SCRL_UP":
      hold: $$lucide:chevron-up$$
      shifted: ''
      tap: $$phosphor:regular/mouse-simple$$
    "&msc SCRL_DOWN":
      hold: $$lucide:chevron-down$$
      shifted: ''
      tap: $$phosphor:regular/mouse-simple$$
    "&msc SCRL_LEFT":
      hold: $$lucide:chevron-left$$
      shifted: ''
      tap: $$phosphor:regular/mouse-simple$$
    "&msc SCRL_RIGHT":
      hold: $$lucide:chevron-right$$
      shifted: ''
      tap: $$phosphor:regular/mouse-simple$$

    # Mouse Cursor Movement
    "&mmv MOVE_LEFT":
      hold: $$lucide:chevron-left$$
      shifted: ''
      tap: $$lucide:mouse-pointer-2$$
    "&mmv MOVE_RIGHT":
      hold: $$lucide:chevron-right$$
      shifted: ''
      tap: $$lucide:mouse-pointer-2$$
    "&mmv MOVE_UP":
      hold: $$lucide:chevron-up$$
      shifted: ''
      tap: $$lucide:mouse-pointer-2$$
    "&mmv MOVE_DOWN":
      hold: $$lucide:chevron-down$$
      shifted: ''
      tap: $$lucide:mouse-pointer-2$$

    # Mouse Clicks
    "&mkp LCLK":
      tap: $$phosphor:regular/mouse-left-click$$
    "&mkp RCLK":
      tap: $$phosphor:regular/mouse-right-click$$
    "&mkp MCLK":
      tap: $$phosphor:regular/mouse-middle-click$$
    "&mkp MB1":
      tap: $$phosphor:regular/mouse-left-click$$
    "&mkp MB2":
      tap: $$phosphor:regular/mouse-right-click$$
    "&mkp MB3":
      tap: $$phosphor:regular/mouse-middle-click$$
    "&mkp MB4":
      tap: $$phosphor:regular/arrow-bend-up-left$$
    "&mkp MB5":
      tap: $$phosphor:regular/arrow-bend-up-right$$

    # Empty
    "&none":
      tap: $$tabler:time-duration-off$$
      type: none

    # Bluetooth
    "&bt BT_CLR": $$phosphor:regular/bluetooth-slash$$
    "&bt BT_SEL": $$phosphor:regular/bluetooth-connected$$
    "&bt BT_SEL 0":
      tap: $$phosphor:regular/bluetooth-connected$$
      hold: 1
    "&bt BT_SEL 1":
      tap: $$phosphor:regular/bluetooth-connected$$
      hold: 2
    "&bt BT_SEL 2":
      tap: $$phosphor:regular/bluetooth-connected$$
      hold: 3
    "&bt BT_SEL 3":
      tap: $$phosphor:regular/bluetooth-connected$$
      hold: 4
    "&bt BT_SEL 4":
      tap: $$phosphor:regular/bluetooth-connected$$
      hold: 5
    "&bt BT_PRV":
      tap: $$phosphor:regular/bluetooth-connected$$
      hold: $$phosphor:regular/caret-left$$
    "&bt BT_NXT":
      tap: $$phosphor:regular/bluetooth-connected$$
      hold: $$phosphor:regular/caret-right$$

    # Output
    "&out OUT_BLE": $$lucide:bluetooth$$
    "&out OUT_USB": $$lucide:usb$$

    # Power
    "&ext_power EP_OFF":
      tap: $$lucide:power-off$$
    "&ext_power EP_ON":
      tap: $$lucide:power$$

    # System 
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

  # ZMK
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    N1: '1'
    N2: '2'
    N3: '3'
    N4: '4'
    N5: '5'
    N6: '6'
    N7: '7'
    N8: '8'
    N9: '9'
    N0: '0'

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$

    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:apple-keyboard-command$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    LEFT_COMMAND: $$mdi:apple-keyboard-command$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:apple-keyboard-command$$
    RIGHT_COMMAND: $$mdi:apple-keyboard-command$$

    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$

    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$

    PSCRN: $$mdi:printer-outline$$
    PAGE_UP: 'PgUp'
    PAGE_DOWN: 'PgDn'
    INSERT: 'Ins'
    "&caps_word": $$mdi:alpha-w-box$$

    # Arrows
    UP: $$lucide:chevron-up$$
    UP_ARROW: $$lucide:chevron-up$$
    DOWN: $$lucide:chevron-down$$
    DOWN_ARROW: $$lucide:chevron-down$$
    LEFT_ARROW: $$lucide:chevron-left$$
    LEFT: $$lucide:chevron-left$$
    RIGHT: $$lucide:chevron-right$$
    RIGHT_ARROW: $$lucide:chevron-right$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$lucide:volume-x$$
    C_VOL_UP: $$lucide:volume-2$$
    C_VOL_DN: $$lucide:volume-1$$
    C_VOLUME_UP: $$lucide:volume-2$$
    C_VOLUME_DOWN: $$lucide:volume-1$$

    # Media
    C_NEXT: $$phosphor:regular/skip-forward$$
    C_PREVIOUS: $$phosphor:regular/skip-back$$
    C_PP: $$phosphor:regular/play-pause$$
    C_PLAY_PAUSE: $$phosphor:regular/play-pause$$

    # Brightness
    C_BRIGHTNESS_INC: $$lucide:sun$$
    C_BRI_UP: $$lucide:sun$$
    C_BRI_INC: $$lucide:sun$$
    C_BRI_DN: $$lucide:sun-dim$$
    C_BRI_DEC: $$lucide:sun-dim$$
    C_BRIGHTNESS_DEC: $$lucide:sun-dim$$

  zmk_combos:
    tmux_prefix:
      key: "$$simple_icons:tmux$$"
    terminal_prefix:
      key: "$$phosphor:regular/terminal$$"
    leader_key_mac_os:
      key: "$$phosphor:regular/keyboard$$"
